-- Repeatable development data.
-- Demo passwords are SHA-256 values generated by MySQL and are not for production.

USE campus_flash_sale;
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

START TRANSACTION;

INSERT INTO users (username, password_hash, role, status) VALUES
    ('admin', SHA2('admin123', 256), 'ADMIN', 'ACTIVE'),
    ('student01', SHA2('123456', 256), 'USER', 'ACTIVE'),
    ('student02', SHA2('123456', 256), 'USER', 'ACTIVE'),
    ('student03', SHA2('123456', 256), 'USER', 'ACTIVE'),
    ('student04', SHA2('123456', 256), 'USER', 'ACTIVE'),
    ('student05', SHA2('123456', 256), 'USER', 'ACTIVE'),
    ('student06', SHA2('123456', 256), 'USER', 'ACTIVE'),
    ('student07', SHA2('123456', 256), 'USER', 'ACTIVE'),
    ('student08', SHA2('123456', 256), 'USER', 'ACTIVE'),
    ('student09', SHA2('123456', 256), 'USER', 'ACTIVE'),
    ('student10', SHA2('123456', 256), 'USER', 'ACTIVE')
ON DUPLICATE KEY UPDATE
    password_hash = VALUES(password_hash),
    role = VALUES(role),
    status = VALUES(status);

INSERT INTO products (
    product_no,
    seller_id,
    title,
    description,
    original_price_cents,
    status
) VALUES (
    'PROD-BOOK-001',
    (SELECT id FROM users WHERE username = 'student01'),
    '数据库系统概论教材',
    '九成新，附带课程重点笔记。',
    5900,
    'IN_FLASH_SALE'
) ON DUPLICATE KEY UPDATE
    seller_id = VALUES(seller_id),
    title = VALUES(title),
    description = VALUES(description),
    original_price_cents = VALUES(original_price_cents),
    status = VALUES(status);

INSERT INTO products (
    product_no,
    seller_id,
    title,
    description,
    original_price_cents,
    status
) VALUES (
    'PROD-BIKE-001',
    (SELECT id FROM users WHERE username = 'student02'),
    '校园通勤自行车',
    '车况良好，适合校内通勤。',
    35000,
    'IN_FLASH_SALE'
) ON DUPLICATE KEY UPDATE
    seller_id = VALUES(seller_id),
    title = VALUES(title),
    description = VALUES(description),
    original_price_cents = VALUES(original_price_cents),
    status = VALUES(status);

INSERT INTO products (
    product_no,
    seller_id,
    title,
    description,
    original_price_cents,
    status
) VALUES (
    'PROD-HEADSET-001',
    (SELECT id FROM users WHERE username = 'student01'),
    'USB 头戴式耳机',
    '功能正常，已完成一次历史抢购演示。',
    9900,
    'SOLD'
) ON DUPLICATE KEY UPDATE
    seller_id = VALUES(seller_id),
    title = VALUES(title),
    description = VALUES(description),
    original_price_cents = VALUES(original_price_cents),
    status = VALUES(status);

INSERT INTO products (
    product_no,
    seller_id,
    title,
    description,
    original_price_cents,
    status
) VALUES (
    'PROD-KEYBOARD-001',
    (SELECT id FROM users WHERE username = 'student02'),
    '87 键机械键盘',
    '青轴键盘，支持正常商品列表查询。',
    12900,
    'ON_SALE'
) ON DUPLICATE KEY UPDATE
    seller_id = VALUES(seller_id),
    title = VALUES(title),
    description = VALUES(description),
    original_price_cents = VALUES(original_price_cents),
    status = VALUES(status);

INSERT INTO flash_sale_activities (
    activity_no,
    product_id,
    flash_price_cents,
    total_stock,
    available_stock,
    start_time,
    end_time,
    status
) VALUES (
    'ACT-BOOK-001',
    (SELECT id FROM products WHERE product_no = 'PROD-BOOK-001'),
    3900,
    10,
    10,
    NOW(3) - INTERVAL 1 HOUR,
    NOW(3) + INTERVAL 7 DAY,
    'ACTIVE'
) ON DUPLICATE KEY UPDATE
    product_id = VALUES(product_id),
    flash_price_cents = VALUES(flash_price_cents),
    start_time = VALUES(start_time),
    end_time = VALUES(end_time),
    status = VALUES(status);

INSERT INTO flash_sale_activities (
    activity_no,
    product_id,
    flash_price_cents,
    total_stock,
    available_stock,
    start_time,
    end_time,
    status
) VALUES (
    'ACT-BIKE-001',
    (SELECT id FROM products WHERE product_no = 'PROD-BIKE-001'),
    29900,
    2,
    2,
    NOW(3) + INTERVAL 1 DAY,
    NOW(3) + INTERVAL 3 DAY,
    'PENDING'
) ON DUPLICATE KEY UPDATE
    product_id = VALUES(product_id),
    flash_price_cents = VALUES(flash_price_cents),
    start_time = VALUES(start_time),
    end_time = VALUES(end_time),
    status = VALUES(status);

INSERT INTO flash_sale_activities (
    activity_no,
    product_id,
    flash_price_cents,
    total_stock,
    available_stock,
    start_time,
    end_time,
    status
) VALUES (
    'ACT-HEADSET-001',
    (SELECT id FROM products WHERE product_no = 'PROD-HEADSET-001'),
    6900,
    1,
    0,
    NOW(3) - INTERVAL 3 DAY,
    NOW(3) - INTERVAL 2 DAY,
    'ENDED'
) ON DUPLICATE KEY UPDATE
    product_id = VALUES(product_id),
    flash_price_cents = VALUES(flash_price_cents),
    start_time = VALUES(start_time),
    end_time = VALUES(end_time),
    status = VALUES(status);

INSERT INTO orders (
    order_no,
    user_id,
    activity_id,
    product_id,
    product_title_snapshot,
    purchase_price_cents,
    quantity,
    total_amount_cents,
    status
)
SELECT
    'ORD-SEED-0001',
    u.id,
    a.id,
    p.id,
    p.title,
    a.flash_price_cents,
    1,
    a.flash_price_cents,
    'CREATED'
FROM users AS u
JOIN flash_sale_activities AS a
    ON a.activity_no = 'ACT-HEADSET-001'
JOIN products AS p
    ON p.id = a.product_id
WHERE u.username = 'student03'
ON DUPLICATE KEY UPDATE
    order_no = VALUES(order_no);

INSERT INTO inventory_logs (
    activity_id,
    order_id,
    change_amount,
    stock_after,
    reason
)
SELECT
    o.activity_id,
    o.id,
    -1,
    0,
    'FLASH_SALE_DEDUCT'
FROM orders AS o
WHERE o.order_no = 'ORD-SEED-0001'
ON DUPLICATE KEY UPDATE
    stock_after = VALUES(stock_after);

COMMIT;
